logging:
  level:
    root: INFO
    com:
      us:
        togoisperf:
          servicemaids: DEBUG
      zaxxer:
        hikari: DEBUG
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
#  file:
#    name: logs/login.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"